apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: rancher-master-l2-announcement-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - ^ens.*$
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
